sudo: required
language: java

jdk:
  - oraclejdk8

matrix:
  include:
  - os: linux
  - os: osx
    env: build_kotlin_native=true
  - os: osx
	env: build_kotlin_native=true kotlin_native_rev=4a461026582d1adb1e7adafe096e56e905d99289

install:
  - nvm install 8
  - nvm use 8
  - node --version
  - npm -g install mocha
  - which node
  - which mocha

script:
  - ./travis_exec.sh
