sudo: required
language: java

jdk:
  - oraclejdk8

#matrix:
#  include:
#  - env: build_kotlin_native=true
#  - env: build_kotlin_native=false

install:
  - nvm install 8
  - nvm use 8
  - node --version
  - npm -g install mocha
  - which node
  - which mocha

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew -s check install && pushd samples && ../gradlew -s check && popd
