sudo: required
language: java

jdk:
  - oraclejdk8

install:
  - nvm install 8
  - nvm use 8
  - node --version
  - npm -g install mocha
  - which node
  - which mocha

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew :korge-native:install
  - cd samples
  - find ~/.m2/repository/com/soywiz
  - ./gradlew :sample1-native:compileDebugKotlinNative
