version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat check --info --no-daemon

branches:
  only:
    - master
    - devel

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - build_kotlin_native: true

matrix:
  fast_finish: true

