version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - appveyor_exec.bat

branches:
  only:
    - master
    - devel

cache:
  - C:\Users\appveyor\.gradle
  - C:\Users\appveyor\.konan

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    build_kotlin_native: true

matrix:
  fast_finish: true

